### ISSUE TITLE
'Tree' object has no attribute 'get_tree' for plotting dendogram

### ISSUE THREAD

**Issue by SBottani** [SENeC-Initiative/DeNSE#22]
No more showing of a neurite dendogram of branchings by using object syntax. Eg.

not working:
> tree = n.axon.get_tree()
> tree.show_dendrogram()

working instead:
 > ds.plot.plot_dendrogram(n.axon) 

See for instance /examples/neurons.chandelier-cell.py
at the very end

**Comment by Silmathoron** [comment]
Solved by #28
