### ISSUE TITLE
create_neurites() has no neurite_angles parameter

### ISSUE THREAD

**Issue by SBottani** [SENeC-Initiative/DeNSE#27]
Hi again Tanguy, last issue for the moment -promised-

Using the latest compiled version  from freshly pulled SENeC-Initiative master, the `create_neurites() `method doesn't work as newly expected and documented in the [doc](https://dense.readthedocs.io/en/latest/user/neuronal_elements.html). 

To be sure of no conflict of version I even removed `dense-0.1.0-py3.8-linux-x86_64.egg` for `/python3.8/site-package` before compiling.

See example below:

My input
```

In [2]: from dense.units import *                                                                                                                           
In [3]: neuron = ds.create_neurons(params={"position": (0., 0.)*um})                                                                                        
In [4]: neuron.create_neurites(num_neurites=3,neurite_angles= {"axon": 15, "dendrite_1": 60, "dendrite_2": 180})       
```                                     

Output
```

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-8e85eed7398b> in <module>
----> 1 neuron.create_neurites(num_neurites=3,neurite_angles= {"axon": 15, "dendrite_1": 60, "dendrite_2": 180})

TypeError: create_neurites() got an unexpected keyword argument 'neurite_angles'
```

**Comment by SBottani** [comment]
Possibly you forgot to merge something before commit #20 

Checked source` /pymodule/_pygrowth.pyx `line 337 : code is still the old one

```
def create_neurites(neurons, num_neurites=1, params=None, angles=None,
                    neurite_types=None, names=None):
```

Best

**Comment by Silmathoron** [comment]
Hi @SBottani there is no error here, as shown in the code you posted, the argument expected by the function is ``angles`` and not ``neurite_angles``.
