### ISSUE TITLE
Recorder does not work

### ISSUE THREAD

**Issue by SBottani** [SENeC-Initiative/DeNSE#34]
Hi again,

This issue concerns the recorder in the example file of previous issue #33 : [file](https://github.com/SENeC-Initiative/DeNSE/files/4498905/res_po_rt_neuron_simple_simulation.zip) 

` python   ds.plot.plot_recording(rec, show=False)`

gives

```python
_pygrowth.pyx in dense._pygrowth._get_recorder_data()

OverflowError: cannot convert float infinity to integer
```

whatever the recorder type tries.

I am just starting looking at recorders, so I may not ot it or have latest syntax, sorry.

Best
Samuel

**Comment by Silmathoron** [comment]
This bug is actually related to an incorrect value returned by ``ds.get_kernel_status("resolution")``, I'm looking into it

**Comment by Silmathoron** [comment]
OK, I found the error: ``resolution`` was an integer instead of a float and there is currently no type check for that kind of things (because it would be very complicated to implement)... I'll try to come up with a way of checking for that...
