### ISSUE TITLE
Breathe package cannot be imported from Linux Mint freshly installed

### ISSUE THREAD

**Issue by kolorblind** [SENeC-Initiative/DeNSE#49]
when installing DeNSE from a fresh version of Linux Mint 

> > ./install_debian.sh
install works well up until

Collecting breathe
  Using cached https://files.pythonhosted.org/packages/2b/4a/bc1bdf34b258e64d9d65869820da927a8995ed9b6edce933b4e11b35848f/breathe-4.19.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-QeRQ8u/breathe/setup.py", line 11, in <module>
        import breathe
      File "breathe/__init__.py", line 10
        def setup(app: Sphinx):
                     ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-QeRQ8u/breathe/

DeNSE seems like it works despite this

**Comment by Silmathoron** [comment]
Hi there, yes, ``breathe`` is only required to build the documentation so this will not prevent you from using DeNSE.
My guess is that they stopped supporting Python 2 and that your Linux Mint still uses Python 2 as the default Python.

**Comment by Silmathoron** [comment]
@kolorblind do you have other questions related to this issue?
If not I'd close it.

**Comment by kolorblind** [comment]
I do not have any other questions related to this issue, thanks!

________________________________
De : Tanguy Fardet <notifications@github.com>
Envoyé : lundi 6 juillet 2020 13:03
À : SENeC-Initiative/DeNSE <DeNSE@noreply.github.com>
Cc : kolorblind <jeremie_mb@outlook.com>; Mention <mention@noreply.github.com>
Objet : Re: [SENeC-Initiative/DeNSE] Breathe package cannot be imported from Linux Mint freshly installed (#49)


@kolorblind<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkolorblind&data=02%7C01%7C%7C33be734300b64a97d4ce08d8219c27d8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637296301844924324&sdata=7XZyWEnLy8bH36cmadtYoivwJIbQY4Sc0F7yzsCTsBA%3D&reserved=0> do you have other questions related to this issue?
If not I'd close it.
